# Generated by Django 3.0.7 on 2020-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
