# Generated by Django 3.0.7 on 2020-06-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200626_2012'),
        ('posts', '0008_wishlist'),
    ]

    operations = [
    ]
