# Generated by Django 3.0.7 on 2020-06-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200627_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='categories',
            field=models.ManyToManyField(blank=True, to='posts.Category'),
        ),
    ]
