# Generated by Django 3.0.7 on 2020-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200627_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='posts.Category'),
        ),
    ]
