# Generated by Django 3.0.7 on 2020-07-01 07:06

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
